export const GetItemPermission = [
  {
    id: 1,
    name: "Administrador",
    description: "Administrador del sistema",
    Inicio: 1,
    Final: 4,
  },
  {
    id: 2,
    name: "Ciudades",
    description: "Administrador de ciudades",
    Inicio: 5,
    Final: 8,
  },
  {
    id: 3,
    name: "Categoria de paquetes",
    description: "Administrador del categoria de paquetes",
    Inicio: 9,
    Final: 12,
  },
  {
    id: 4,
    name: "Casilleros",
    description: "Administrador de casilleros",
    Inicio: 13,
    Final: 16,
  },
  {
    id: 5,
    name: "Paquetes",
    description: "Administrador de paquetes",
    Inicio: 17,
    Final: 20,
  },
  {
    id: 6,
    name: "Costo de envio",
    description: "Administrador de los costos de envio",
    Inicio: 21,
    Final: 24,
  },
  {
    id: 7,
    name: "Seguimiento",
    description: "Administrador de seguimiento",
    Inicio: 25,
    Final: 28,
  },
  {
    id: 8,
    name: "Tipos de paquetes",
    description: "Administrador de paquetes",
    Inicio: 29,
    Final: 32,
  },
  {
    id: 9,
    name: "Direcciones",
    description: "Administrador de direcciones",
    Inicio: 33,
    Final: 36,
  },
  {
    id: 10,
    name: "Paises",
    description: "Administrador de paises",
    Inicio: 37,
    Final: 40,
  },
  {
    id: 11,
    name: "Clientes",
    description: "Administrador del clientes",
    Inicio: 41,
    Final: 44,
  },
  {
    id: 12,
    name: "Correos electronicos",
    description: "Administrador de correos electronicos",
    Inicio: 45,
    Final: 48,
  },
  {
    id: 13,
    name: "Personas",
    description: "Administrador de personas",
    Inicio: 49,
    Final: 52,
  },
  {
    id: 14,
    name: "Telefonos",
    description: "Administrador de telefonos",
    Inicio: 53,
    Final: 56,
  },
  {
    id: 15,
    name: "Departamentos",
    description: "Administrador de departamentos",
    Inicio: 57,
    Final: 60,
  },
  {
    id: 16,
    name: "Roles de usuarios",
    description: "Administrador de roles de usuarios",
    Inicio: 61,
    Final: 64,
  },
  {
    id: 17,
    name: "Usuarios",
    description: "Administrador de usuarios",
    Inicio: 65,
    Final: 68,
  },
  {
    id: 18,
    name: "Metodos de pago",
    description: "Administrador del metodo de pago",
    Inicio: 69,
    Final: 72,
  },
  {
    id: 19,
    name: "Facturas",
    description: "Administrador de facturas",
    Inicio: 73,
    Final: 76,
  },
];
